season: "2019"
casting_complete: false
css_version: 4
future: false
maintainer_email: don@postplayhouse.com
box_office_phone: "1-888-665-1976"
tickets_link: https://postplayhousetickets.universitytickets.com

# Site settings
title: Post Playhouse
email: don@happycollision.com
twitter: postplayhouse
facebook: post.playhouse
description: >
  Post Playhouse, Inc. is Northwestern Nebraska's favorite live theatre company, producing several musicals running in a repertory schedule every summer by bringing together highly skilled creative professionals from across the country and nearby. Post Playhouse, Inc. performs its productions at the theatre in Fort Robinson State Park.
baseurl: "/jekyll.postplayhouse.com"
url: "https://postplayhouse.github.io" # the base hostname & protocol for your site

# Build settings
permalink: /news/:year/:month/:day/:title/
excerpt_separator: <!--more-->

exclude:
  - .bowerrc
  - .gitignore
  - bower.json
  - yarn.lock
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

timezone: US/Mountain
locale: en_us
icon: /images/post-playhouse-logo.png
